### PR TITLE
WIP Attempt fix for websockets over secure connection.

### PR DESCRIPTION
**Pull request by diversemix**
Not been able to test locally. Testing on demo site, as its down anyhow.

### CODE REVIEW

**Comment by diversemix** [comment]
Merging to be able to perform a test

**Comment by giorgiosironi** [comment]
No problem with the change, but need to sort out testing in Vagrant and <swearword>graceful degradation</swearword>

**Comment by diversemix** [comment]
Thanks - although I am now thinking we need to revert this - as this is not where the HTTP <-> HTTPS proxying is done. At least I assume not as there are no certs here :) ... I guess there is some sort of config for this in AWS?

**Comment by giorgiosironi** [comment]
nginx is configured by default with a certificate: https://github.com/elifesciences/builder-base-formula/blob/master/elife/config/etc-nginx-nginx.conf so `listen 443 ssl` is usually everything that is needed to support HTTPS.

**Comment by giorgiosironi** [comment]
(and it is there in the `server` stanza in this case)

**Pull request merged**
