### PR TITLE
Introduce pillar.elife_xpub.orcid.sandbox

### PR DESCRIPTION
**Pull request by giorgiosironi**
Follow-up to https://github.com/elifesciences/elife-xpub-deployment/pull/11

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Our Salt is too old (2017) to have the `tojson` filter.

**Comment by giorgiosironi** [comment]
Depends on https://github.com/elifesciences/builder-configuration/pull/2

**Comment by giorgiosironi** [comment]
Cannot be built without the dependency https://github.com/elifesciences/builder-configuration/pull/2

**Comment by diversemix** [comment]
ok ... just approved that... do we need to prod the checks again?

**Comment by giorgiosironi** [comment]
Yes, replaying pipeline at https://alfred.elifesciences.org/blue/organizations/jenkins/pull-requests-projects%2Felife-xpub-formula/detail/PR-35/3/pipeline

The content of this is an environment variable that doesn't touch configuration files so it may be fine to get in.

**Comment by giorgiosironi** [comment]
This is a non-secret environment configuration, so it should be dealt with with `NODE_CONFIG_ENV` instead choosing a `config/*.js` file.

**Pull request closed without merging**
